### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by Dylantje** [endysh/Wireless-PIR-sensor#1]
Dear..
What is the hardware u use...
And what is the sketch?

**Comment by RoelandK** [comment]
Hey,

Well a Pir sensor 

Verstuurd vanaf mijn iPhone

**Comment by endysh** [comment]
I reused the original sensor from the light

Thank you,
endy

-----Original Message-----

**Comment by Dylantje** [comment]
and how did u use a sketch?
And how did u use the radio for mysensors?

**Comment by endysh** [comment]
Hi,

Here is the example sketch for MySensors I wrote about 2 years ago.
https://github.com/endysh/Wireless-PIR-sensor/blob/master/firmware/MySensorNode/MySensorNode.ino
Most likely it is quite outdated already, I did not have a chance to adapt
it to the latest version of MySensors framework

Thank you.
Andrey

**Comment by sijeffrey** [comment]
Hi Andrey,

I would really like to construct a wireless PIR like yours. Could I get a copy of the PCB? What format is it in?

Thanks,
Simon.

**Comment by endysh** [comment]
Hi Simon,

The PCB files can be found under hardware folder.
There are three files:

arduino_pir_sensor.pdf - this is schematic in PDF format

Two others are in EAGLE CAD formats
arduino_pir_sensor.sch - schematics
arduino_pir_sensor.brd - PCB

You will need either to find a PCB manufacturer accepting EAGLE format or
export PCB to Gerber format which most PCB houses accept, using EAGLE CAD

Thank you,
Andrey
